### ISSUE TITLE
cannot load such file -- rubygems/format

### ISSUE THREAD

**Issue by pigmonkey** [minad/pacgem#12]
I receive the following error when trying to install a gem:

```
/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require': cannot load such file -- rubygems/format (LoadError)
    from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /usr/bin/pacgem:423:in `load_libraries'
    from /usr/bin/pacgem:451:in `process'
    from /usr/bin/pacgem:404:in `run'
    from /usr/bin/pacgem:560:in `<main>'
```

**Comment by minad** [comment]
fixed

**Comment by joelibaceta** [comment]
@minad how did you fixed ?
